### ISSUE TITLE
No sound in firefox

### ISSUE THREAD

**Issue by toxinu** [tooxie/shiva-client#2]
Thanks for this great shiva client! :smile: 
But when I play a music in Firefox 20 (Ubuntu 64bits) no sound start, I just have this error message:

![Screenshot at 2013-03-12 19:32:50](https://f.cloud.github.com/assets/293337/250233/8c1bdcc8-8b43-11e2-884c-9cfe77c2769e.png)

**Comment by kepstin** [comment]
This is probably due to firefox not supporting MP3 audio. Try a different browser, or the branch of shiva-server that has ogg support, perhaps.

**Comment by tooxie** [comment]
Try the [shiva-server's oggsupport branch](https://github.com/tooxie/shiva-server/tree/oggsupport) and [shiva-client's oggsupport branch](https://github.com/tooxie/shiva-client/tree/oggsupport) as well. They introduce backward-incompatible changes to the API, that's why I'm being careful to merge them.

I'll mark this ticket as invalid. Thanks for the report.
